services:
  node-installer:
    image: node:20.17.0
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm i

  vue:
    image: node:20.17.0
    container_name: vue
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm run dev:vue
    depends_on:
      node-installer:
        condition: service_completed_successfully

  nestjs:
    image: node:20.17.0
    container_name: nestjs
    volumes:
      - ./:/home/node/project
    ports:
      - 5555:5555
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm run dev:nestjs
    depends_on:
      node-installer:
        condition: service_completed_successfully

  fastify:
    image: node:20.17.0
    container_name: fastify
    volumes:
      - ./:/home/node/project
    ports:
      - 3000:3000
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm run dev:fastify
    depends_on:
      node-installer:
        condition: service_completed_successfully

  postgres:
    image: postgres:16.6
    env_file: ./back-app/src/infrastructure/database/prisma/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    attach: false

  mongo-viewer:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: ./back-app/src/infrastructure/database/mongoose/.env

  mongo:
    image: mongo
    env_file: ./back-app/src/infrastructure/database/mongoose/.env
    volumes:
      - "mongo_data:/data/db"
    attach: false

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - vue
      - nestjs
    attach: false

volumes:
  postgres_data:
  mongo_data:
